name: app4geracao
description: Aplicativo de agendamento de cotes de cabelo para barbearia 4 geração

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_mobx: ^1.0.1
  cupertino_icons: ^0.1.2
  mobx: ^1.0.2+2
  flare_splash_screen: ^3.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.7.3
  flutter_native_splash: ^0.1.9
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.0
  mobx_codegen: ^1.0.2
  url_launcher: ^5.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: gloucester
      fonts:
        - asset: assets/font/GloucesterOSMTPro.otf
        - asset: assets/font/GloucesterMTPro-Bold.otf
          weight: 700
    - family: rutheride
      fonts:
        - asset: assets/font/Rutheride.otf
        - asset: assets/font/Rutheride.otf
          weight: 700

flutter_native_splash:
  image: assets/images/logo_black.png
  color: "BFBCAA"
  android_disable_fullscreen: true
