name: app4geracao
description: Aplicativo de agendamento de cotes de cabelo para barbearia 4 geração

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^1.0.1
  cupertino_icons: ^0.1.2
  mobx: ^1.0.2+2
  flare_splash_screen: ^3.0.1
  http: ^0.12.1
  shared_preferences: ^0.5.7+2
  uuid: ^2.0.4
  image_picker: ^0.6.6+1
  path: ^1.6.4
  permission_handler: ^5.0.0+hotfix.6
  flutter_icons: ^1.0.0+1
  camera_camera: ^1.0.32+1
  page_transition: ^1.1.5
  mask_text_input_formatter: ^1.0.6
  intl: ^0.16.1
  image: ^2.1.12
  flutter_masked_text: ^0.7.0
  carousel_slider: ^2.1.0
  table_calendar: ^2.2.3
  flutter_rating_bar: ^3.0.1+1

dev_dependencies:
  flutter_launcher_icons: ^0.7.3
  flutter_native_splash: ^0.1.9
  build_runner: ^1.8.0
  mobx_codegen: ^1.0.2
  url_launcher: ^5.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: gloucester
      fonts:
        - asset: assets/font/GloucesterOSMTPro.otf
        - asset: assets/font/GloucesterMTPro-Bold.otf
          weight: 700
    - family: rutheride
      fonts:
        - asset: assets/font/Rutheride.otf
        - asset: assets/font/Rutheride.otf
          weight: 700
    - family: athiti
      fonts:
        - asset: assets/font/athiti-regular.ttf
        - asset: assets/font/athiti-semi-bold.ttf
          weight: 700
    - family: antonio
      fonts:
        - asset: assets/font/antonio-regular.ttf
        - asset: assets/font/antonio-bold.ttf
          weight: 700

flutter_native_splash:
  image: assets/images/logo_black.png
  color: "BFBCAA"
  android_disable_fullscreen: true
